AWSTemplateFormatVersion: 2010-09-09
Description: |
  this is IAM Role templates
Parameters:
  IAMrolename:
    Description: input your role name
    Type: String
    Default: role-servicename

Resources:
  IAMroleID:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      RoleName: !Ref IAMrolename